/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SERVIDOR
 */
public class PrincipalII extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalII
     */
    public PrincipalII() {
        initComponents();
        JButton botonesH[]={cmdCrear,cmdLimpiar};
        JButton botonesD[]={cmdLlenadoManual,cmdOperacion,cmdLlenadoAuto};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroFilas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroColumnas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoAuto = new javax.swing.JButton();
        cmdOperacion = new javax.swing.JButton();
        cmdLlenadoManual = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        cmbOperaciones = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("MATRICES II");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos iniciales:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Numero de filas:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtNumeroFilas.setBackground(new java.awt.Color(255, 204, 255));
        txtNumeroFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroFilasKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Numero de columnas:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtNumeroColumnas.setBackground(new java.awt.Color(255, 204, 255));
        txtNumeroColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroColumnasKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 290, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 40));

        cmdLlenadoAuto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdLlenadoAuto.setText("Llenado Automatico");
        cmdLlenadoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAutoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 40));

        cmdOperacion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdOperacion.setText("Operacion");
        cmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionActionPerformed(evt);
            }
        });
        jPanel3.add(cmdOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, 40));

        cmdLlenadoManual.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdLlenadoManual.setText("Llenado Manual");
        cmdLlenadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 40));

        cmdLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 380, 150));

        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 430, 290));

        cmbOperaciones.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Letra B", "Letra K", "Letra M", "Letra W", "Letra Q", "Letra J", "Letra G", "Letra R", "Figura No.1", "Figura No.2", "Figura No.3", "Figura No.4" }));
        cmbOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 120, 30));

        tblTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablaResultado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 440, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 560));

        setSize(new java.awt.Dimension(1099, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int nf,nc;
        DefaultTableModel tm,tm2;
       if (txtNumeroFilas.getText().trim().isEmpty()){
           txtNumeroFilas.requestFocusInWindow();
          JOptionPane.showMessageDialog(this,"Digite por favor el numero de filas","Error",JOptionPane.ERROR_MESSAGE);
        } else if (txtNumeroColumnas.getText().trim().isEmpty()){
            txtNumeroColumnas.requestFocusInWindow();
            JOptionPane.showMessageDialog(this,"Digite por favor el numero de columnas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else {
            
            nf=Integer.parseInt(txtNumeroFilas.getText());
            nc=Integer.parseInt(txtNumeroColumnas.getText());
            
            if (nc != nf) {
            Helper.mensaje(this, "Digite el mismo numero de filas y columnas", 2);
            txtNumeroFilas.setText("");
            txtNumeroColumnas.setText("");
            txtNumeroFilas.requestFocusInWindow();
            
        } else if (nf == 0) {
            Helper.mensaje(this, "Por favor, digite un numero diferente", 3);
            txtNumeroFilas.requestFocusInWindow();
            txtNumeroFilas.selectAll();
            
        } else if (nc == 0) {
            Helper.mensaje(this, "Por favor, digite un numero diferente", 3);
            txtNumeroColumnas.selectAll();
            
        }else if (nf%2==0){
          Helper.mensaje(this, "Por favor, digite un numero impar", 2);
          txtNumeroFilas.setText("");
          txtNumeroColumnas.setText("");
          txtNumeroFilas.requestFocusInWindow();
          
        } else if (nc%2==0){
          Helper.mensaje(this, "Por favor, digite un numero impar", 2);
          txtNumeroFilas.setText("");
          txtNumeroColumnas.setText("");
          txtNumeroFilas.requestFocusInWindow();
          
        } else if (nf<=5 && nc<=5){
            Helper.mensaje(this, "Digite un numero mayor que 5",3);
          txtNumeroFilas.setText("");
          txtNumeroColumnas.setText("");
          txtNumeroFilas.requestFocusInWindow(); 
          
        }else{
         tm = (DefaultTableModel) tblTablaInicial.getModel();
         tm2 = (DefaultTableModel) tblTablaResultado.getModel();

         tm.setRowCount(nf);
         tm.setColumnCount(nc);

         tm2.setRowCount(nf);
         tm2.setColumnCount(nc);
         
        JButton botonesH[] = {cmdLlenadoAuto, cmdLlenadoManual, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdOperacion};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
         
        }
       } 
        
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenadoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAutoActionPerformed
        int nf,nc,n;
        
        nf=Integer.parseInt(txtNumeroFilas.getText());
        nc=Integer.parseInt(txtNumeroColumnas.getText());
        
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
               n = (int) (Math.random()*50 + 1); 
              tblTablaInicial.setValueAt(n,i,j);  
            }
        }
        JButton botonesH[]={cmdOperacion,cmdLimpiar};
        JButton botonesD[]={cmdCrear,cmdLlenadoAuto,cmdLlenadoManual};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);  
    }//GEN-LAST:event_cmdLlenadoAutoActionPerformed

    private void cmdLlenadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoManualActionPerformed
       int nf, nc;
       int n;
        int sw, res;

        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elemeto en la posicion ["+i+"]"+"["+j+"]").trim());
                        tblTablaInicial.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un numero valido",3);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = nf;
                            j = nc;
                            
                            Helper.porDefectoTabla(tblTablaInicial);
                            Helper.porDefectoTabla(tblTablaResultado);
                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesH[]={cmdOperacion,cmdLimpiar};
        JButton botonesD[]={cmdLlenadoManual,cmdCrear,cmdLlenadoAuto};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLlenadoManualActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
       int nf,nc;
       
      nc=tblTablaInicial.getColumnCount();
      nf=tblTablaInicial.getRowCount();
      DefaultTableModel tm,tm2;
      
      txtNumeroColumnas.setText("");
      txtNumeroFilas.setText("");
      cmbOperaciones.setSelectedIndex(0);
      
      tm=(DefaultTableModel) tblTablaInicial.getModel();
      tm2=(DefaultTableModel) tblTablaResultado.getModel();
      
       tm.setRowCount(0);
       tm.setColumnCount(0);
       
       tm2.setRowCount(0);
       tm2.setColumnCount(0);
       
       JButton botonesH[]={cmdCrear,cmdLimpiar};
       JButton botonesD[]={cmdLlenadoManual,cmdOperacion,cmdLlenadoAuto};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionActionPerformed
        int nf,nc,op,aux;
      
        op = cmbOperaciones.getSelectedIndex();
        Helper.limpiartabla(tblTablaResultado);
        
      switch (op){
            case 0:
              Helper.LetraB (tblTablaInicial, tblTablaResultado);
                break;
            case 1:
             Helper.LetraK(tblTablaInicial, tblTablaResultado);
                break;
            case 2:
             Helper.LetraM(tblTablaInicial, tblTablaResultado);
                break;
            case 3:
             Helper.LetraW(tblTablaInicial, tblTablaResultado);
                break; 
             case 4:
             Helper.LetraQ(tblTablaInicial, tblTablaResultado);
                break;
           case 5:
             Helper.LetraJ(tblTablaInicial, tblTablaResultado);
                break;
            case 6:
            Helper.LetraG(tblTablaInicial, tblTablaResultado);   
               break;
           case 7:
            Helper.LetraR(tblTablaInicial, tblTablaResultado);   
               break; 
            case 8:
            Helper.PrimeraFigura(tblTablaInicial, tblTablaResultado);   
               break;   
           case 9:
            Helper.SegundaFigura(tblTablaInicial, tblTablaResultado);   
               break;
           case 10:
              Helper.TerceraFigura(tblTablaInicial, tblTablaResultado);
              break;
                
           case 11:
              Helper.CuartaFigura(tblTablaInicial, tblTablaResultado);
               break;
      }
        JButton botonesH[]={cmdOperacion,cmdLimpiar};
        JButton botonesD[]={cmdCrear,cmdLlenadoAuto,cmdLlenadoManual};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdOperacionActionPerformed

    private void cmbOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperacionesActionPerformed
       
    }//GEN-LAST:event_cmbOperacionesActionPerformed

    private void txtNumeroFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFilasKeyTyped
       char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumeroFilasKeyTyped

    private void txtNumeroColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroColumnasKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumeroColumnasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOperaciones;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenadoAuto;
    private javax.swing.JButton cmdLlenadoManual;
    private javax.swing.JButton cmdOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTable tblTablaResultado;
    private javax.swing.JTextField txtNumeroColumnas;
    private javax.swing.JTextField txtNumeroFilas;
    // End of variables declaration//GEN-END:variables
}
